version: "3.9"

services:
  web:
    build: .
    command: python /bookstore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bookstore
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-ch5$!1!$$s@6=a7dvhzfzqlek5(4ixj_98j+o8s2(++yg^^y(!"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
volumes:
  postgres_data: